---
workflow:
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  - if: '$CI_COMMIT_TAG'
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
- test
- publish

variables:
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}/cv-builder
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

include:
- local: '/.gitlab/ci/docker-gitlab-ci.yml'
- local: '/.gitlab/ci/cv-gitlab-ci.yml'
