---
stages:
- test
- build
- publish

variables:
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}/cv-builder
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
  #RELEASE_CV_FILENAME: cv-DanAnglin-${CI_COMMIT_REF_NAME}.pdf
  RELEASE_CV_FILENAME: cv-DanAnglin-2020.08.09.pdf

include:
- template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
- local: '/.gitlab/ci/docker-gitlab-ci.yml'
- local: '/.gitlab/ci/cv-gitlab-ci.yml'
