---
.use-cv-builder:
  image: ${IMAGE_NAME}:master-8b42c9fd

.test-conditions:
  only:
    refs:
    - merge_requests
  except:
    changes:
    - docker/Dockerfile
    - __output/*

test:spellcheck:
  before_script:
  - apt-get update
  - apt-get -y install aspell make
  extends:
  - .test-conditions
  image: ubuntu:18.04
  stage: test
  script:
  - make spellcheck
  only:
    refs:
    - merge_requests

test:pdf:
  artifacts:
    expire_in: 1 hour
    paths:
    - __output/cv.pdf
  extends:
  - .use-cv-builder
  - .test-conditions
  before_script:
  - make clean
  stage: test
  script:
  - make

publish:pdf:
  extends: .use-cv-builder
  before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 0400 ~/.ssh/known_hosts
  - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - git config --global user.name "${GITLAB_USER_NAME}"
  - make clean
  stage: publish
  script:
  - make
  - git checkout master
  - git add __output/cv.pdf
  - 'git commit -m "auto: update CV."'
  - git push origin master
  only:
    refs:
    - master@dananglin/cv
  except:
    changes:
    - docker/Dockerfile
    - __output/*
