---
#--------------------------------------------#
# Hidden job templates for CV build pipeline #
#--------------------------------------------#
.use-cv-builder:
  image: ${IMAGE_NAME}:master-cb8a29c7

.cv-default-job-rules:
  rules:
  - when: always

.cv-release-rules:
  rules:
  #- if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "dananglin/cv"'
  - if: '$CI_COMMIT_REF_NAME =~ /^[0-9]{4}(.[0-9]{2}){2}$/ && $CI_PROJECT_PATH == "dananglin/cv"'
    when: always

.default-tags:
  tags:
  - dananglin-general

.release-tags:
  tags:
  - dananglin-cv-release

#------------------------------------#
# Visible jobs for CV build pipeline #
#------------------------------------#

test:spellcheck:
  before_script:
  - apt-get update
  - apt-get -y install aspell aspell-en
  extends:
  - .cv-default-job-rules
  - .default-tags
  - .use-cv-builder
  script:
  - go run mage.go spellcheck
  stage: test

test:pdf:
  extends:
  - .cv-default-job-rules
  - .default-tags
  - .use-cv-builder
  script:
  - go run mage.go pdf
  stage: test

build:pdf:
  artifacts:
    expire_in: "10 minutes"
    name: cv-DanAnglin-${CI_COMMIT_REF_NAME}
    paths:
    - __output/cv.pdf
    - build_job_id
  extends:
  - .cv-default-job-rules
  - .default-tags
  - .use-cv-builder
  needs:
  - job: "test:spellcheck"
    artifacts: false
  - job: "test:pdf"
    artifacts: false
  script:
  - go run mage.go pdf
  - echo "${CI_JOB_ID}" > build_job_id
  stage: build

#publish:pdf:
#  extends:
#  - .cv-publish-rules
#  - .default-tags
#  - .use-cv-builder
#  before_script:
#  - eval $(ssh-agent -s)
#  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#  - mkdir -p ~/.ssh && chmod 700 ~/.ssh
#  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
#  - chmod 0400 ~/.ssh/known_hosts
#  - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
#  - git config --global user.email "${GITLAB_USER_EMAIL}"
#  - git config --global user.name "${GITLAB_USER_NAME}"
#  stage: publish
#  script:
#  - go run mage.go pdf
#  - git checkout master
#  - git add __output/cv.pdf
#  - 'git commit -m "auto: [skip ci] update CV."'
#  - git push origin master

release:pdf:online:
  extends:
  - .cv-release-rules
  - .release-tags
  image: alpine:3.12
  needs:
  - job: "build:pdf"
    artifacts: true
  script:
  - ls -la
  stage: publish
  variables:
    GIT_STRATEGY: "none"

release:pdf:private:
  extends:
  - .cv-release-rules
  - .release-tags
  - .use-cv-builder
  needs:
  - job: "test:spellcheck"
    artifacts: false
  - job: "test:pdf"
    artifacts: false
  script:
  - go run mage.go pdf
  - mv __output/cv.pdf ${CV_DEPLOY_DIR}/${RELEASE_CV_FILENAME}
  stage: publish
  variables:
    CV_DEPLOY_DIR: "/CV"
    CV_CONTACT_PHONE: $RELEASE_CV_CONTACT_PHONE
